#!/bin/bash

ERRORSTRING="Error. Please make sure you've indicated correct parameters"
if [ $# -eq 0 ]
    then
        echo $ERRORSTRING;
#elif [ $1 == "live" ]
#    then
#        if [[ -z $2 ]]
#            then
#                echo "Running dry-run"
#                rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./public/* root@thebrandingplug.com:/var/www/yessicaduque.com/html
#        elif [ $2 == "go" ]
#            then
#                echo "Running actual deploy"
#                rsync -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./public/* root@thebrandingplug.com:/var/www/yessicaduque.com/html
#        else
#            echo $ERRORSTRING;
#        fi
elif [ $1 == "staging" ]
    then
        if [[ -z $2 ]]
            then
                echo "Running dry-run"
                rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./public/* root@thebrandingplug.com:/var/www/staging/tikatours/html
        elif [ $2 == "go" ]
            then
                echo "Running actual deploy"
                rsync -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./public/* root@thebrandingplug.com:/var/www/staging/tikatours/html
        else
            echo $ERRORSTRING;
        fi
elif [ $1 == "github" ]
    then
        if [[ -z $2 ]]
            then
               echo "Specify commit message"
               exit(1)
        else
            rsync -r ~/pcode/tikatours.com/public/ ~/deploy/tikatours.com/
            git add .
            git commit $2
            git push -u origin master
        fi
else
    echo $ERRORSTRING;
fi